### ISSUE TITLE
Survey state isn't being saved

### ISSUE THREAD

**Issue by odhlen** [slavefreetradegithub/libertas_people#35]
If I leave mid survey then I have to start the survey all over again. It wont bring me back to the last question I answered.

**Comment by MichaelKMalak** [comment]
I can't reproduce the issue for some reason
<img src="http://g.recordit.co/pK66Mh3sCf.gif"/>

**Comment by odhlen** [comment]
What happens when you just leave the survey and go back to the home page, then try to take the survey? Does the button say 'Take Survey' or 'Finish Survey'?
